export const MEMBER = {
  firstName: "Alex",
  phase: "Active Transformation",
};

export const PHASES = [
  "Starting",
  "Active Transformation",
  "Lifestyle Phase",
  "Maintenance",
  "Clinician-Guided Exception",
];

export const TODAY_CARDS = [
  { key: "hydration", label: "Hydration check", value: "62 / 96 oz", progress: 64, hint: "Two more glasses before 6pm" },
  { key: "protein", label: "Protein protected?", value: "88 / 130 g", progress: 67, hint: "Add a 30g portion at dinner" },
  { key: "medication", label: "Medication rhythm", value: "Next dose Sun · 8:00am", progress: 100, hint: "Thigh rotation due this week" },
  { key: "tolerance", label: "Tolerance status", value: "Calm", progress: 18, hint: "No flagged symptoms today" },
  { key: "emotional", label: "Emotional check-in", value: "Steady", progress: 72, hint: "Logged 3 min ago" },
  { key: "bodycare", label: "PYPER Body-Care Plan", value: "AM done · PM pending", progress: 50, hint: "Texture Rx tonight · SPF logged" },
  { key: "training", label: "Training rhythm", value: "Strength · 42 min", progress: 80, hint: "Pilates scheduled tomorrow" },
  { key: "provider", label: "Questions for provider", value: "2 open", progress: 30, hint: "Bring to next check-in" },
];

export const REMINDERS_TODAY = [
  { time: "07:30", label: "PYPER reminder: body-care routine", type: "Body-care" },
  { time: "09:00", label: "Hydration check", type: "Hydration" },
  { time: "12:30", label: "Protein check", type: "Protein" },
  { time: "12:00", label: "PYPER reminder: sun protection check", type: "SPF" },
  { time: "20:00", label: "PYPER reminder: body-care routine", type: "Body-care" },
  { time: "20:30", label: "Emotional check-in", type: "Mental" },
];

export const CHAPTERS = [
  { id: "start", title: "Start Here", time: "4 min", tag: "Onboarding" },
  { id: "safety", title: "Medical & Member Safety", time: "6 min", tag: "Safety" },
  { id: "method", title: "The PYPER Method", time: "8 min", tag: "Foundation" },
  { id: "pillars", title: "Seven PYPER Pillars", time: "10 min", tag: "Foundation" },
  { id: "phases", title: "Three-Phase Standard", time: "7 min", tag: "Framework" },
  { id: "window", title: "The Medication Window", time: "9 min", tag: "GLP-1" },
  { id: "composition", title: "Body Composition", time: "8 min", tag: "Physical" },
  { id: "nutrition", title: "Metabolic Nutrition", time: "12 min", tag: "Nutrition" },
  { id: "dining", title: "Dining, Travel & Social Protocols", time: "9 min", tag: "Lifestyle" },
  { id: "training", title: "Supplements, Strength & Movement", time: "11 min", tag: "Physical" },
  { id: "skin", title: "Skin & Body Refinement", time: "9 min", tag: "Dermatology" },
  { id: "recovery", title: "Recovery, Mindset & Maintenance", time: "8 min", tag: "Mindset" },
  { id: "tracking", title: "Tracking, Safety & Red Flags", time: "7 min", tag: "Safety" },
  { id: "beyond", title: "Beyond GLP-1", time: "10 min", tag: "Maintenance" },
  { id: "appendix", title: "Appendices & Member Tools", time: "5 min", tag: "Tools" },
];

export const PILLARS = [
  { n: "01", title: "Clinical Foundation", body: "Work with a licensed clinician. Every protocol begins with prescribed care and informed consent." },
  { n: "02", title: "Metabolic Nutrition", body: "Protein-protected meals, fiber, electrolytes, and disciplined hydration support the medication window." },
  { n: "03", title: "Strength & Movement", body: "Resistance training preserves lean mass. Pilates refines posture, mobility, and core control." },
  { n: "04", title: "Skin & Body Refinement", body: "Barrier-first dermatology supports the visible transformation as composition shifts." },
  { n: "05", title: "Recovery & Sleep", body: "Sleep and recovery anchor tolerance, mood, and metabolic response." },
  { n: "06", title: "Mindset & Emotional Care", body: "Emotional adjustment is part of the protocol — not an afterthought." },
  { n: "07", title: "Maintenance Discipline", body: "Lifestyle phase is where the work compounds. Maintenance is the brand." },
];

export const TRACKERS = [
  { id: "body", name: "Body Metrics", note: "Weight · waist · hips · chest · arm · thigh" },
  { id: "medication", name: "Medication Rhythm", note: "Dose · site · missed-dose handling" },
  { id: "supplements", name: "Supplement Routine", note: "Clinician-approved · time taken" },
  { id: "tolerance", name: "Tolerance Tracker", note: "Severity sliders · red-flag logic" },
  { id: "emotional", name: "Emotional Check-In", note: "Mood · sleep · body image" },
  { id: "nutrition", name: "Protein + Hydration", note: "Targets · steppers · sliders" },
  { id: "training", name: "Training Rhythm", note: "Strength · Pilates · steps" },
  { id: "skin", name: "PYPER Body-Care Plan", note: "Plan · applications · SPF · tolerance" },
];

export const OFFERS = [
  {
    brand: "Ritual Protein",
    title: "Essential Protein Daily",
    category: "Protein",
    type: "Affiliate Link",
    reason: "Clean third-party tested protein that supports the medication window.",
    benefit: "15% off your first three orders",
    disclosure: "Affiliate link. PYPER may earn commission.",
  },
  {
    brand: "LMNT",
    title: "Zero-sugar electrolytes",
    category: "Hydration",
    type: "Member Partner Offer",
    reason: "Sodium, potassium, magnesium for hydration discipline.",
    benefit: "Free sample pack with purchase",
    disclosure: "Partner offer. PYPER may receive compensation from this brand.",
  },
  {
    brand: "SkinCeuticals",
    title: "Barrier-first regimen",
    category: "Skin + Body Care",
    type: "Guide Exclusive",
    reason: "Dermatology-grade actives paired for sensitive transformation skin.",
    benefit: "Member-only consultation",
    disclosure: "Partner offer. PYPER may receive compensation from this brand.",
  },
  {
    brand: "Equinox",
    title: "Pilates + Strength",
    category: "Pilates",
    type: "Member Partner Offer",
    reason: "Reformer Pilates programming aligned to lean-mass preservation.",
    benefit: "Waived initiation for PYPER members",
    disclosure: "Partner offer. PYPER may receive compensation from this brand.",
  },
  {
    brand: "Factor",
    title: "Protein-forward meal prep",
    category: "Meal Prep",
    type: "Affiliate Link",
    reason: "Helps members hit protein targets on travel weeks.",
    benefit: "$120 off across five boxes",
    disclosure: "Affiliate link. PYPER may earn commission.",
  },
  {
    brand: "Hydrant",
    title: "Travel hydration sachets",
    category: "Travel",
    type: "Member Partner Offer",
    reason: "Portable electrolytes for clinic days and travel.",
    benefit: "20% off + free shipping",
    disclosure: "Partner offer. PYPER may receive compensation from this brand.",
  },
];

export const PROGRESS_SERIES = [
  { week: "W1", weight: 184, protein: 78, tolerance: 4 },
  { week: "W2", weight: 182, protein: 82, tolerance: 3 },
  { week: "W3", weight: 181, protein: 88, tolerance: 5 },
  { week: "W4", weight: 179, protein: 90, tolerance: 2 },
  { week: "W5", weight: 178, protein: 94, tolerance: 2 },
  { week: "W6", weight: 176, protein: 96, tolerance: 3 },
  { week: "W7", weight: 175, protein: 98, tolerance: 1 },
  { week: "W8", weight: 173, protein: 101, tolerance: 2 },
];

export const SAFETY_ITEMS = [
  {
    title: "Urgent red flags",
    body: "Severe abdominal pain, repeated vomiting, inability to hydrate, fainting, chest pain, allergic reaction, suicidal thoughts, or severe mental health concerns may require urgent medical attention. Contact your clinician or seek urgent/emergency care. Do not rely on this guide for urgent medical decisions.",
  },
  {
    title: "Missed-dose guidance",
    body: "Follow your prescriber's instructions for missed doses. Do not double dose unless directed by your clinician.",
  },
  {
    title: "Mental health crisis",
    body: "If you feel unsafe or at risk of harming yourself, contact your clinician, crisis support, or emergency services immediately. This guide does not provide therapy or crisis intervention.",
  },
  {
    title: "Supplement caution",
    body: "Discuss any new supplement with your clinician, especially when taking GLP-1 or other prescribed medications.",
  },
  {
    title: "Body-care irritation",
    body: "Pause actives at first signs of barrier compromise. Barrier first, actives second.",
  },
];

export const RED_FLAG_KEYS = ["abdominalPain", "vomiting", "noHydrate"];


export const BODY_CARE_PLAN_PRODUCTS = [
  {
    id: "pigment-rx",
    productName: "Pigment Rx Body Serum",
    brand: "PYPER Clinical Body Care",
    productType: "PYPER Clinical Body Care",
    pathway: "Pigment",
    tier: "Rx",
    activeIngredient: "Azelaic acid compound",
    strength: "15%",
    formulation: "Serum",
    prescriberName: "Dr. Elaine Mercer",
    planStatus: "Clinician-Approved",
    treatmentPurpose: "Guide-supported pigment routine",
    bodyArea: "Chest",
    prescribedAmount: "thin layer",
    amountUnit: "thin layer",
    frequency: "Every other day",
    daysOfWeek: "Monday, Wednesday, Friday",
    timeOfDay: "PM",
    startDate: "2026-06-01",
    endDate: "2026-08-31",
    reviewDate: "2026-07-15",
    cycleOrRestPeriod: "6 weeks active, reassess before increasing",
    layeringOrder: "2",
    specialInstructions: "Apply only to listed zones. Avoid open or irritated skin.",
    spfRequired: true,
    refillReminder: "2026-07-01",
    notes: "Prescribed plan remains the source of truth.",
  },
  {
    id: "texture-rx",
    productName: "Texture Rx Smoothing Cream",
    brand: "PYPER Clinical Body Care",
    productType: "PYPER Clinical Body Care",
    pathway: "Texture",
    tier: "Rx+",
    activeIngredient: "Tretinoin compound",
    strength: "0.025%",
    formulation: "Cream",
    prescriberName: "Dr. Elaine Mercer",
    planStatus: "Clinician-Entered",
    treatmentPurpose: "Texture routine for upper arms",
    bodyArea: "Upper arms",
    prescribedAmount: "pea-sized amount",
    amountUnit: "pea-sized amount",
    frequency: "Custom days",
    daysOfWeek: "Monday, Wednesday, Friday",
    timeOfDay: "PM",
    startDate: "2026-06-01",
    endDate: "2026-09-01",
    reviewDate: "2026-07-15",
    cycleOrRestPeriod: "Rest one night after irritation above 5/10 if clinician instructed",
    layeringOrder: "2",
    specialInstructions: "Moisturizer first if skin feels dry. Do not apply after shaving.",
    spfRequired: true,
    refillReminder: "2026-07-08",
    notes: "Do not change frequency unless clinician provides instructions.",
  },
  {
    id: "recover",
    productName: "Recover Barrier Balm",
    brand: "PYPER Clinical Body Care",
    productType: "PYPER Clinical Body Care",
    pathway: "Recover",
    tier: "Maintain",
    activeIngredient: "Ceramide complex",
    strength: "Barrier support",
    formulation: "Balm",
    prescriberName: "Dr. Elaine Mercer",
    planStatus: "Clinician-Approved",
    treatmentPurpose: "Barrier recovery",
    bodyArea: "Upper arms, Chest",
    prescribedAmount: "thin layer",
    amountUnit: "thin layer",
    frequency: "Daily",
    daysOfWeek: "Every night",
    timeOfDay: "PM",
    startDate: "2026-06-01",
    endDate: "",
    reviewDate: "2026-07-15",
    cycleOrRestPeriod: "Use nightly during active cycles",
    layeringOrder: "3",
    specialInstructions: "Apply after prescription actives unless clinician says otherwise.",
    spfRequired: false,
    refillReminder: "2026-07-20",
    notes: "Fictional demo product.",
  },
  {
    id: "spf",
    productName: "Mineral Body SPF 50",
    brand: "PYPER SPF Edit",
    productType: "Non-Prescription",
    pathway: "Recover",
    tier: "Maintain",
    activeIngredient: "Zinc oxide",
    strength: "SPF 50",
    formulation: "Lotion",
    prescriberName: "",
    planStatus: "Patient-Entered",
    treatmentPurpose: "Sun protection support",
    bodyArea: "Chest, Shoulders, Upper arms, Hands",
    prescribedAmount: "prescribed amount",
    amountUnit: "prescribed amount",
    frequency: "Daily",
    daysOfWeek: "When exposed",
    timeOfDay: "AM",
    startDate: "2026-06-01",
    endDate: "",
    reviewDate: "",
    cycleOrRestPeriod: "Reapply with outdoor exposure",
    layeringOrder: "4",
    specialInstructions: "Privacy-safe reminders only. No prescription details on lock screen.",
    spfRequired: true,
    refillReminder: "2026-07-10",
    notes: "Discuss SPF preferences with clinician if skin is reactive.",
  },
  {
    id: "cleanser",
    productName: "Fragrance-Free Body Cleanser",
    brand: "Demo Dermatology",
    productType: "Non-Prescription",
    pathway: "Calm",
    tier: "Maintain",
    activeIngredient: "Gentle surfactant blend",
    strength: "Non-prescription",
    formulation: "Cleanser",
    prescriberName: "",
    planStatus: "Self-Added · Not Yet Reviewed",
    treatmentPurpose: "Cleanse without fragrance",
    bodyArea: "Back, Chest, Shoulders",
    prescribedAmount: "custom instruction",
    amountUnit: "custom instruction",
    frequency: "Daily",
    daysOfWeek: "Daily",
    timeOfDay: "After shower",
    startDate: "2026-06-03",
    endDate: "",
    reviewDate: "2026-07-15",
    cycleOrRestPeriod: "As tolerated",
    layeringOrder: "1",
    specialInstructions: "Self-added product. Add to clinician questions before changing prescription plan.",
    spfRequired: false,
    refillReminder: "",
    notes: "Not yet reviewed.",
  },
  {
    id: "moisturizer",
    productName: "Fragrance-Free Body Moisturizer",
    brand: "Demo Dermatology",
    productType: "Non-Prescription",
    pathway: "Calm",
    tier: "Maintain",
    activeIngredient: "Glycerin and ceramides",
    strength: "Non-prescription",
    formulation: "Cream",
    prescriberName: "",
    planStatus: "Patient-Entered",
    treatmentPurpose: "Moisture support",
    bodyArea: "Upper arms, Back, Thighs",
    prescribedAmount: "thin layer",
    amountUnit: "thin layer",
    frequency: "Daily",
    daysOfWeek: "Daily",
    timeOfDay: "After shower",
    startDate: "2026-06-01",
    endDate: "",
    reviewDate: "",
    cycleOrRestPeriod: "Use as needed for comfort",
    layeringOrder: "1",
    specialInstructions: "May support barrier comfort. Discuss persistent irritation with clinician.",
    spfRequired: false,
    refillReminder: "",
    notes: "Fictional demo product.",
  },
];

export const BODY_AREA_ROUTINES = [
  { area: "Upper arms", time: "PM Routine", items: ["Texture Rx · Monday, Wednesday, Friday", "Recover · Every night"] },
  { area: "Back", time: "After shower", items: ["Fragrance-free cleanser · Daily", "Fragrance-free moisturizer · Daily"] },
  { area: "Chest", time: "PM Routine", items: ["Pigment Rx · Monday, Wednesday, Friday", "Recover · Every night"] },
  { area: "Shoulders", time: "AM + SPF", items: ["Mineral Body SPF 50 · When exposed"] },
];

export const BODY_CARE_TODAY_ROUTINE = [
  { id: "am-spf", timeOfDay: "AM", bodyArea: "Chest, Shoulders, Upper arms, Hands", productName: "Mineral Body SPF 50", productType: "Non-Prescription", amount: "prescribed amount", instructions: "Apply before outdoor exposure. Reapply if swimming or sweating.", spfRequirement: "SPF required", dueStatus: "Due" },
  { id: "shower-cleanser", timeOfDay: "After shower", bodyArea: "Back, Chest, Shoulders", productName: "Fragrance-Free Body Cleanser", productType: "Non-Prescription", amount: "custom instruction", instructions: "Use gentle pressure. Avoid scrubbing irritated skin.", spfRequirement: "No SPF requirement", dueStatus: "Complete" },
  { id: "pm-texture", timeOfDay: "PM", bodyArea: "Upper arms", productName: "Texture Rx Smoothing Cream", productType: "PYPER Clinical Body Care", amount: "pea-sized amount", instructions: "Monday, Wednesday, Friday. Apply only to upper arms.", spfRequirement: "SPF required tomorrow", dueStatus: "Pending" },
  { id: "pm-recover", timeOfDay: "PM", bodyArea: "Upper arms, Chest", productName: "Recover Barrier Balm", productType: "PYPER Clinical Body Care", amount: "thin layer", instructions: "Layer after active products unless clinician says otherwise.", spfRequirement: "No SPF requirement", dueStatus: "Pending" },
  { id: "training-spf", timeOfDay: "After training", bodyArea: "Shoulders, Upper arms, Hands", productName: "Mineral Body SPF 50", productType: "Non-Prescription", amount: "prescribed amount", instructions: "Reapply if outdoor training, swimming, or sweating occurred.", spfRequirement: "SPF reapplication support", dueStatus: "Not due" },
];

export const BODY_CARE_APPLICATION_LOG = [
  { date: "2026-06-03", timeApplied: "20:15", product: "Texture Rx Smoothing Cream", bodyArea: "Upper arms", amountApplied: "pea-sized amount", appliedAsPrescribed: "Yes", status: "Applied as planned", moisturizerLayered: true, spfUsed: true, reapplicationNeeded: false, irritationAfter: false, notes: "No deviation from plan." },
  { date: "2026-06-02", timeApplied: "20:45", product: "Pigment Rx Body Serum", bodyArea: "Chest", amountApplied: "thin layer", appliedAsPrescribed: "No", status: "Applied partially", moisturizerLayered: true, spfUsed: true, reapplicationNeeded: false, irritationAfter: true, notes: "Used half amount due to dryness. Prescribed plan unchanged." },
  { date: "2026-06-01", timeApplied: "21:00", product: "Recover Barrier Balm", bodyArea: "Upper arms", amountApplied: "thin layer", appliedAsPrescribed: "Yes", status: "Held per clinician", moisturizerLayered: true, spfUsed: false, reapplicationNeeded: false, irritationAfter: false, notes: "Texture Rx held per clinician instruction; Recover continued." },
];

export const BODY_CARE_SPF_PLAN = {
  spfProduct: "Mineral Body SPF 50",
  spfLevel: "50",
  exposedBodyAreas: "Chest, shoulders, upper arms, hands",
  usualApplicationTime: "AM",
  outdoorExposureExpected: true,
  swimmingOrSweatingExpected: false,
  reapplicationReminderPreference: "Every 2 hours during outdoor exposure",
  waterResistant: true,
  notes: "Reminder text stays generic for privacy.",
};

export const BODY_CARE_SPF_TRACKING = {
  appliedToday: true,
  bodyAreasCovered: "Chest, shoulders, upper arms, hands",
  reapplicationCompleted: false,
  skippedReason: "",
  notes: "Reapplication may be due before afternoon walk.",
};

export const BODY_CARE_TOLERANCE_TREND = [
  { week: "W1", dryness: 2, irritation: 2, itching: 1, flare: 0, spf: 78 },
  { week: "W2", dryness: 3, irritation: 3, itching: 2, flare: 1, spf: 82 },
  { week: "W3", dryness: 4, irritation: 5, itching: 3, flare: 1, spf: 86 },
  { week: "W4", dryness: 3, irritation: 4, itching: 2, flare: 0, spf: 91 },
];

export const BODY_CARE_PLAN_VERSIONS = [
  { version: "Plan Version 2", effectiveDate: "2026-06-15", createdDate: "2026-06-10", changedBy: "Dr. Elaine Mercer", reasonForChange: "Texture Rx frequency adjusted after dryness pattern review", previousPlanArchived: true, status: "Active" },
  { version: "Plan Version 1", effectiveDate: "2026-06-01", createdDate: "2026-05-28", changedBy: "Dr. Elaine Mercer", reasonForChange: "Initial body-care plan", previousPlanArchived: false, status: "Archived" },
];

export const BODY_CARE_QUESTIONS = [
  { priority: "High", question: "Irritation increased from 2 to 5 this week on upper arms. Should I keep the same Texture Rx schedule?", source: "Skin Progress" },
  { priority: "Medium", question: "Can I keep using the non-prescription moisturizer with Pigment Rx?", source: "My Plan" },
  { priority: "Medium", question: "When should SPF be reapplied on training days?", source: "SPF tracking" },
];

export const BODY_CARE_SUPPORT_PRODUCTS = [
  { name: "Fragrance-free body moisturizer", category: "Barrier support", reason: "May support comfort when prescription actives feel drying.", caution: "Discuss with your clinician if irritation persists or if you use prescription body-care products." },
  { name: "UPF wrap or sun shirt", category: "Sun protection", reason: "Commonly used for member convenience during outdoor exposure.", caution: "Does not replace clinician guidance or SPF instructions." },
];
